db:
  type: mariadb
  host: mars-flip-mariadb-dev.crushi2l5fpc.ap-northeast-2.rds.amazonaws.com
  port: 3306
  username: mars_flip
  password: mars00--
  database: mars_flip
  synchronize: true

jwt:
  secret: mars-flip-secret-key-dev-mars-flip-secret-key-dev-mars-flip-secret-key-dev
  refreshSecret: refresh-mars-flip-secret-key-dev-refresh-mars-flip-secret-key-dev-refresh-mars-flip-secret-key-dev
