db:
  type: sqlite
  database: database.db
  synchronize: true

jwt:
  secret: mars-flip-secret-key-dev-mars-flip-secret-key-dev-mars-flip-secret-key-dev
  refreshSecret: refresh-mars-flip-secret-key-dev-refresh-mars-flip-secret-key-dev-refresh-mars-flip-secret-key-dev
