db:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: 0118
  database: flip
  synchronize: true

jwt:
  secret: mars-flip-secret-key-dev-mars-flip-secret-key-dev-mars-flip-secret-key-dev
